swagger: "2.0"
info:
  version: "1.0.0"
  title: "Product API"
  description: "API for managing products"
paths:
  /products:
    get:
      summary: Get all the products
      tags:
        - Products managed by Admin
      responses:
        200:
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/Product"
    post:
      summary: Create a new product
      tags:
        - Products managed by Admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/Product"
      responses:
        201:
          description: Product created successfully
        400:
          description: Bad request. Check your request body for any errors or missing fields.
        403:
          description: Forbidden. You do not have permission to access this resource.
        404:
          description: Not found. The requested resource was not found.
        500:
          description: Internal server error. Please try again later or contact support.
  /products/{id}:
    get:
      summary: Get a product by ID
      tags:
        - Products managed by Admin
      parameters:
        - name: id
          in: path
          description: ID of the product to retrieve
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Product found
          content:
            application/json:
              schema:
                $ref: "#/definitions/Product"
        404:
          description: Product not found
    put:
      summary: Update a product by ID
      tags:
        - Products managed by Admin
      parameters:
        - name: id
          in: path
          description: ID of the product to update
          required: true
          type: integer
          format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/Product"
      responses:
        200:
          description: Product updated successfully
        404:
          description: Product not found
    delete:
      summary: Delete a product by ID
      tags:
        - Products managed by Admin
      parameters:
        - name: id
          in: path
          description: ID of the product to delete
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Product deleted successfully
        404:
          description: Product not found

definitions:
  Product:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 1
      product_brand_name:
        type: string
        example: "Nike"
      product_description:
        type: string
        example: "Running shoes with breathable mesh upper"
      product_category:
        type: string
        example: "Men's footwear"
      product_price:
        type: number
        format: float
        example: 99.99
      product_rating:
        type: number
        format: float
        example: 4.5
      product_total_quantity:
        type: integer
        format: int64
        example: 900
      create_date:
        type: string
        format: date-time
        example: "2023-07-25T05:36:24.983Z"
      update_date:
        type: string
        format: date-time
        example: "2023-08-15T10:20:30.456Z"


    example:
      id: 1
      product_brand_name: "Nike"
      product_description: "Running shoes with breathable mesh upper"
      product_category: "Men's footwear"
      product_price: 99.99
      product_rating: 4.5
      product_total_quantity: 900
      create_date: "2023-07-25T05:36:24.983Z"
      update_date: "2023-08-15T10:20:30.456Z"
