swagger: "2.0"
info:
  version: "1.0.0"
  title: "Product API"
  description: "API for managing products"
paths:
  /products:
    post:
      summary: Create a new product
      tags:
        - Products Management by Admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/NewProduct"
      responses:
        201:
          description: Product created successfully
        400:
          description: Bad request. Check your request body for any errors or missing fields.
        500:
          description: Internal server error. Please try again later or contact support.

definitions:
  NewProduct:
    type: object
    properties:
      product_brand_name:
        type: string
        example: "Nike"
      product_description:
        type: string
        example: "Running shoes with breathable mesh upper"
      product_category:
        type: string
        example: "menCategory"
      product_price:
        type: number
        format: float
        example: 99.99
      product_image_url:
        type: string
        example: "https://example.com/product-image.jpg"
      sizes:
        type: string
        example: "S:10,M:20,L:15,XL:2,XXL:5"
