swagger: "2.0"
info:
  version: "1.0.0"
  title: "Cart API - POST"
  description: "API for adding new items to user carts"

paths:
  /cart:
    post:
      summary: Add a new item to the user's cart
      tags:
        - User Carts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/AddToCartRequest"
      responses:
        201:
          description: Item added to the cart successfully
          content:
            application/json:
              schema:
                $ref: "#/definitions/CartItem"
        400:
          description: Bad request. Check your request body for any errors or missing fields.
        403:
          description: Forbidden. You do not have permission to access this resource.
        500:
          description: Internal server error. Please try again later or contact support.

definitions:
  AddToCartRequest:
    type: object
    properties:
      user_id:
        type: integer
        format: int64
        example: 21
      product_id:
        type: integer
        format: int64
        example: 1
      product_size:
        type: string
        example: "M"
      product_quantity:
        type: integer
        format: int64
        example: 2

    required:
      - user_id
      - product_id
      - product_quantity
      - product_size

  CartItem:
    type: object
    properties:
      id:
        type: integer
        format: int64
      product_id:
        type: integer
        format: int64
      user_id:
        type: integer
        format: int64
      product_quantity:
        type: integer
        format: int64
      product_size:
        type: string
      product_brand_name:
        type: string
      product_image_url:
        type: string
      product_price:
        type: string
      product_description:
        type: string
    example:
      id: 503
      product_id: 1
      user_id: 21
      product_quantity: 2
      product_size: "M"
      product_brand_name: "Nike"
      product_image_url: "/productImages/menCategory/mendress1.jpeg"
      product_price: "129.99"
      product_description: "Updated product description"
