swagger: "2.0"
info:
  version: "1.0.0"
  title: "Wishlist API"
  description: "API for managing user wishlists"
paths:
  /wishlist:
    get:
      summary: Get user's wishlist items
      tags:
        - User's Wishlist
      responses:
        200:
          description: A list of user's wishlist items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/definitions/Wishlist'
    post:
      summary: Add product to wishlist
      tags:
        - User's Wishlist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/Wishlist'
      responses:
        '200':
          description: Product added to wishlist successfully
    put:
      summary: Update product in wishlist
      tags:
        - User's Wishlist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/Wishlist'
      responses:
        '200':
          description: Product in wishlist updated successfully
    delete:
      summary: Remove product from wishlist
      tags:
        - User's Wishlist
      responses:
        '200':
          description: Product removed from wishlist successfully

definitions:
  Wishlist:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 1
      user_id:
        type: string
        example: "123abc"
      product_id:
        type: integer
        example: 123
      date_added:
        type: string
        format: date-time
        example: "2023-07-25T05:36:24.983Z"

