swagger: "2.0"
info:
  version: "1.0.0"
  title: "User Info API"
  description: "API for managing user information"
paths:
  /userInfo:
    get:
      summary: Get all user information
      tags:
        - User's Info
      responses:
        200:
          description: User information retrieved successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/UserInfo"
        500:
          description: Internal Server Error
    post:
      summary: Create a new user information
      tags:
        - User's Info
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/UserInfo"
      responses:
        201:
          description: User's information created successfully
        400:
          description: Bad request - Invalid input
        500:
          description: Internal Server Error

definitions:
  UserInfo:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 1
      user_full_name:
        type: string
        example: "John Doe"
      user_email:
        type: string
        example: "john@example.com"
      user_phone_number:
        type: string
        example: "1234567890"
      user_age:
        type: integer
        example: 30
      user_gender:
        type: string
        example: "male"
      user_shipping_address:
        type: string
        example: "123 Main St, City, Country"
      user_billing_address:
        type: string
        example: "456 Secondary St, City, Country"
      user_profile_picture_url:
        type: string
        example: "https://example.com/profile.jpg"
      cash_balance:
        type: number
        format: float
        example: 100.00
      create_date:
        type: string
        format: date-time
        example: "2023-07-25T05:36:24.983Z"
      update_date:
        type: string
        format: date-time
        example: "2023-08-15T10:20:30.456Z"
