swagger: "2.0"
info:
  version: "1.0.0"
  title: "Product API"
  description: "API for managing products"
paths:
  /products:
    get:
      summary: Get all the products
      tags:
        - Products for Users
      responses:
        200:
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/Products"

    

  /products/{id}:
    get:
      summary: Get a product by ID
      tags:
        - Products for Users
      parameters:
        - name: id
          in: path
          description: ID of the product to retrieve
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Product found
          content:
            application/json:
              schema:
                $ref: "#/definitions/Products"
              example:
                - id: 1
                  product_brand_name: "Nike"
                  product_description: "Running shoes with breathable mesh upper"
                  product_category: "menCategory"
                  product_price: 99.99
                  product_rating: 4.5
                  product_image_url: "/productImages/menCategory/menfootwear.jpeg"
                  create_date: "2023-07-25T05:36:24.983Z"
                  update_date: "2023-08-15T10:20:30.456Z"
                  product_color: "Blue"
        404:
          description: Product not found

    

definitions:
  Products:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 1
      product_brand_name:
        type: string
        example: "Nike"
      product_description:
        type: string
        example: "Running shoes with breathable mesh upper"
      product_category:
        type: string
        example: "menCategory"
      product_price:
        type: number
        format: float
        example: 99.99
      product_rating:
        type: number
        format: float
        example: 4.5
      product_image_url:
        type: string
        example: "/productImages/menCategory/menfootwear.jpeg"
      create_date:
        type: string
        format: date-time
        example: "2023-07-25T05:36:24.983Z"
      update_date:
        type: string
        format: date-time
        example: "2023-08-15T10:20:30.456Z"
      product_color:
        type: string
        example: "Blue"

