swagger: "2.0"
info:
  version: "1.0.0"
  title: "Product API"
  description: "API for managing products"
paths:
  /products:
    get:
      summary: Get all the products
      tags:
        - Products for Users
      responses:
        200:
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/Product"

definitions:
  Product:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 1
      product_brand_name:
        type: string
        example: "Nike"
      product_description:
        type: string
        example: "Running shoes with breathable mesh upper"
      product_category:
        type: string
        example: "Men's footwear"
      product_price:
        type: number
        format: float
        example: 99.99
      product_rating:
        type: number
        format: float
        example: 4.5
      product_total_quantity:
        type: integer
        format: int64
        example: 900
      create_date:
        type: string
        format: date-time
        example: "2023-07-25T05:36:24.983Z"
      update_date:
        type: string
        format: date-time
        example: "2023-08-15T10:20:30.456Z"

    example:
      id: 1
      product_brand_name: "Nike"
      product_description: "Running shoes with breathable mesh upper"
      product_category: "Men's footwear"
      product_price: 99.99
      product_rating: 4.5
      product_total_quantity: 900
      create_date: "2023-07-25T05:36:24.983Z"
      update_date: "2023-08-15T10:20:30.456Z"
