swagger: "2.0"
info:
  version: "1.0.0"
  title: "User Address API"
  description: "API for managing user addresses"
paths:
  /userAddress:
    post:
      summary: Create a new user address
      tags:
        - User Addresses
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/AddUserAddressInput"
            example:
              user_id: 1
              fullname: John Doe
              mobilenumber: "+1234567890"
              address: "123 Main St"
              localitytown: "Downtown"
              city: "Cityville"
              state: "Stateville"
              zip: "12345"
              country: "Countryland"
              is_default: true
              addresstype: "Home"
      responses:
        201:
          description: User address created successfully
        500:
          description: Internal Server Error

  /userAddress/{userId}:
    get:
      summary: Get all user addresses by user ID
      tags:
        - User Addresses
      parameters:
        - name: userId
          in: path
          description: ID of the user whose addresses to retrieve
          required: true
          type: integer
      responses:
        200:
          description: A list of user addresses
          content:
            application/json:
              schema:
                $ref: "#/definitions/UserAddress"
              example:
                - id: 1
                  userId: 123
                  fullname: John Doe
                  mobilenumber: "+1234567890"
                  address: "123 Main St"
                  localitytown: "Downtown"
                  city: "Cityville"
                  state: "Stateville"
                  zip: "12345"
                  country: "Countryland"
                  is_default: true
                  addresstype: "Home"
        404:
          description: User not found
        500:
          description: Internal Server Error

definitions:
  UserAddress:
    type: object
    properties:
      id:
        type: integer
        format: int64
      user_id:
        type: integer
        format: int64
      fullname:
        type: string
      mobilenumber:
        type: string
      address:
        type: string
      localitytown:
        type: string
      city:
        type: string
      state:
        type: string
      zip:
        type: string
      country:
        type: string
      is_default:
        type: boolean
      addresstype:
        type: string

  AddUserAddressInput:
    type: object
    required:
      - user_id
      - fullname
      - mobilenumber
      - address
      - localitytown
      - city
      - state
      - zip
      - country
      - is_default
      - addresstype
    properties:
      user_d:
        type: integer
      fullname:
        type: string
      mobilenumber:
        type: string
      address:
        type: string
      localitytown:
        type: string
      city:
        type: string
      state:
        type: string
      zip:
        type: string
      country:
        type: string
      is_default:
        type: boolean
      addresstype:
        type: string
