swagger: "2.0"
info:
  version: "1.0.0"
  title: "Wishlist API"
  description: "API for managing user wishlist items"
paths:
  /userWishlist:
    post:
      summary: Create a new wishlist item
      tags:
        - Wishlist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/WishlistItemInput"
      responses:
        201:
          description: Wishlist item created successfully
          content:
            application/json:
              schema:
                $ref: "#/definitions/WishlistItem"
        400:
          description: Bad request
  /userWishlist/{user_id}:
    get:
      summary: Get wishlist items by user ID
      tags:
        - Wishlist
      parameters:
        - in: path
          name: user_id
          description: ID of the user whose wishlist items to retrieve
          required: true
          type: integer
      responses:
        200:
          description: A list of wishlist items for the specified user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/WishlistItem"
        404:
          description: Wishlist items not found for the specified user
  /userWishlist/{user_id}/{product_id}: # Updated path to include product_id
    delete:
      summary: Delete a wishlist item
      tags:
        - Wishlist
      parameters:
        - in: path
          name: user_id
          description: ID of the user who owns the wishlist item
          required: true
          type: integer
        - in: path
          name: product_id
          description: ID of the wishlist item to be deleted
          required: true
          type: integer
      responses:
        204:
          description: Wishlist item deleted successfully
        404:
          description: Wishlist item not found

definitions:
  WishlistItem:
    type: object
    properties:
      product_id:
        type: integer
        example: 1
      user_id:
        type: integer
        example: 21

  WishlistItemInput:
    type: object
    properties:
      product_id:
        type: integer
        example: 1
      user_id:
        type: integer
        example: 21
