swagger: "2.0"
info:
  version: "1.0.0"
  title: "Order API"
  description: "API for managing user orders"
paths:
  /user-orders:
    get:
      summary: Get user's all orders
      tags:
        - User's Orders
      responses:
        200:
          description: A list of user's orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/definitions/UserOrder"

definitions:
  UserOrder:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 1
      user_id:
        type: string
        example: "123abc"
      status:
        type: string
        example: "pending"
      order_payment_type:
        type: string
        example: "credit_card"
      total_price:
        type: number
        format: float
        example: 100.00
      shipping_address:
        type: string
        example: "123 Main St, City, Country"
      billing_address:
        type: string
        example: "456 Secondary St, City, Country"
      payment_status:
        type: string
        example: "paid"
      delivery_status:
        type: string
        example: "shipped"
      order_notes:
        type: string
        example: "Please deliver between 9 am and 5 pm"
      createDate:
        type: string
        format: date-time
        example: "2023-07-25T05:36:24.983Z"
      updateDate:
        type: string
        format: date-time
        example: "2023-08-15T10:20:30.456Z"
